services:
  - type: web
    name: rembg-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    branch: main
    healthCheckPath: /health
    dockerCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: API_KEY
        generateValue: true  # 自动生成一个安全的API Key 